export const banks = [
    { code: "044", name: "Access Bank" },
    { code: "581", name: "Access Y’ello & Beta" },
    { code: "113", name: "AccessMoney" },
    { code: "091", name: "Accion MFB" },
    { code: "975", name: "Addosser Microfinance Bank" },
    { code: "195", name: "Advans La Fayette MFB" },
    { code: "50025", name: "Afemai Microfinance Bank" },
    { code: "51336", name: "AKU Microfinance Bank" },
    { code: "50066", name: "Alvana Microfinance Bank" },
    { code: "90180", name: "Amju Unique MFB" },
    { code: "51341", name: "Ampersand MFB" },
    { code: "401", name: "ASO Savings & Loans" },
    { code: "404", name: "AssetMatrix MFB" },
    { code: "51351", name: "AWACASH Microfinance Bank" },
    { code: "50992", name: "Baobab Microfinance Bank" },
    { code: "50145", name: "BOSAK Microfinance Bank" },
    { code: "40163", name: "Branch International Financial Services" },
    { code: "51153", name: "Brightway Microfinance Bank" },
    { code: "50948", name: "Monarch Microfinance Bank" },
    { code: "120", name: "MoneyBox" },
    { code: "946", name: "MoneyMaster PSB" },
    { code: "50515", name: "Moniepoint MFB" },
    { code: "132", name: "NowNow / Contec Global" },
    { code: "305", name: "OPay" },
    { code: "327", name: "PAGA" },
    { code: "526", name: "Parallex MFB" },
    { code: "311", name: "Parkway-ReadyCash" },
    { code: "105", name: "Premium Trust Bank" },
    { code: "101", name: "Providus Bank" },
    { code: "502", name: "Rand Merchant Bank" },
    { code: "061", name: "Signature Bank" },
    { code: "803", name: "SmartCash PSB" },
    { code: "51062", name: "SOLID ALLIANZE MFB" },
    { code: "51310", name: "Sparkle MFB" },
    { code: "221", name: "Stanbic IBTC Bank" },
    { code: "068", name: "Standard Chartered Bank Nigeria" },
    { code: "232", name: "Sterling Bank" },
    { code: "100", name: "Suntrust Bank" },
    { code: "301", name: "Jaiz Bank / TAJ Bank" },
    { code: "250", name: "Titan Trust Bank" },
    { code: "032", name: "Union Bank of Nigeria" },
    { code: "033", name: "United Bank for Africa (UBA)" },
    { code: "215", name: "Unity Bank" },
    { code: "035", name: "Wema Bank / ALAT" },
    { code: "057", name: "Zenith Bank" },
    { code: "50211", name: "Kuda Bank" },
  ];
  